pipeline {
  agent any

  environment {
    DOCKER_IMAGE = 'dlsqja3436/todak-backend'
    TAG = 'goguma'
    EC2_HOST = 'i13a409.p.ssafy.io'
    COMPOSE_DIR = './backend' 
  }

  stages {
    stage('Build Application') {
      agent {
        docker {
          image 'gradle:7.6-jdk17'
        }
      }
      steps {
        sh '''
          cd ./backend/
          chmod +x ./gradlew
          ./gradlew clean build
        '''
        stash name: 'built-jar', includes: 'backend/build/libs/*.jar'
      }
    }

    stage('Build and Push Docker Image') {
      steps {

        unstash 'built-jar'

        withCredentials([
          usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKERHUB_USERNAME',
            passwordVariable: 'DOCKERHUB_PASSWORD'
          )
        ]) {
          sh '''
            cd ./backend/
            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker build --no-cache -t ${DOCKER_IMAGE}:${TAG} .
            docker push ${DOCKER_IMAGE}:${TAG}
          '''
        }
      }
    }

    stage('Deploy with Docker Compose to EC2') {
      steps {
        withCredentials([
          sshUserPrivateKey(
            credentialsId: 'ec2-ssh-key',
            keyFileVariable: 'KEYFILE',
            usernameVariable: 'EC2_USERNAME'
          ),
          usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKERHUB_USERNAME',
            passwordVariable: 'DOCKERHUB_PASSWORD'
          ),
          usernamePassword(
            credentialsId: 'mysql_secret',
            usernameVariable: 'MYSQL_USERNAME',
            passwordVariable: 'MYSQL_PASSWORD'
          ),
          usernamePassword(
            credentialsId: 'S3_KEY',
            usernameVariable: 'S3_ACCESS_KEY',
            passwordVariable: 'S3_SECRET_KEY'
          ),
          usernamePassword(
            credentialsId: 'rabbitmq',
            usernameVariable: 'MQ_USERNAME',
            passwordVariable: 'MQ_PASSWORD'
          ),
          usernamePassword(
            credentialsId: 'kakao_cred',
            usernameVariable: 'KAKAO_ID',
            passwordVariable: 'KAKAO_SECRET'
          ),
          usernamePassword(
            credentialsId: 'kakao_key',
            usernameVariable: 'KAKAO',
            passwordVariable: 'KAKAO_KEY'
          ),
          usernamePassword(
            credentialsId: 'gms_cred',
            usernameVariable: 'GMS',
            passwordVariable: 'GMS_KEY'
          ),
          usernamePassword(
            credentialsId: 'kakaopay_host',
            usernameVariable: 'KAKAOPAY',
            passwordVariable: 'KAKAOPAY_HOST'
          ),
          usernamePassword(
            credentialsId: 'kakaopay_dev_key',
            usernameVariable: 'KAKAOPAY_KEY',
            passwordVariable: 'KAKAOPAY_DEV_KEY'
          ),
          usernamePassword(
            credentialsId: 'kakaopay_cid_dev',
            usernameVariable: 'KAKAOPAY_CID',
            passwordVariable: 'KAKAOPAY_DEV_CID'
          ),
        ]) {
          sh '''
            chmod 600 "$KEYFILE"

            # EC2에 docker-compose 파일 및 .env 전달
            scp -i "$KEYFILE" -o StrictHostKeyChecking=no ${COMPOSE_DIR}/docker-compose.yml $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/
            echo "DOCKER_IMAGE=${DOCKER_IMAGE}" > ${COMPOSE_DIR}/.env
            echo "TAG=${TAG}" >> ${COMPOSE_DIR}/.env
            echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> ${COMPOSE_DIR}/.env
            echo "MYSQL_USERNAME=$MYSQL_USERNAME" >> ${COMPOSE_DIR}/.env
            echo "S3_ACCESS_KEY=$S3_ACCESS_KEY" >> ${COMPOSE_DIR}/.env
            echo "S3_SECRET_KEY=$S3_SECRET_KEY" >> ${COMPOSE_DIR}/.env

            echo "MQ_USERNAME=$MQ_USERNAME" >> ${COMPOSE_DIR}/.env
            echo "MQ_PASSWORD=$MQ_PASSWORD" >> ${COMPOSE_DIR}/.env

            echo "KAKAO_KEY=$KAKAO_KEY" >> ${COMPOSE_DIR}/.env
            echo "KAKAO_ID=$KAKAO_ID" >> ${COMPOSE_DIR}/.env
            echo "KAKAO_SECRET=$KAKAO_SECRET" >> ${COMPOSE_DIR}/.env

            echo "GMS_KEY=$GMS_KEY" >> ${COMPOSE_DIR}/.env

            echo "KAKAOPAY_HOST=$KAKAOPAY_HOST" >> ${COMPOSE_DIR}/.env
            echo "KAKAOPAY_DEV_KEY=$KAKAOPAY_DEV_KEY" >> ${COMPOSE_DIR}/.env
            echo "KAKAOPAY_DEV_CID=$KAKAOPAY_DEV_CID" >> ${COMPOSE_DIR}/.env

            scp -i "$KEYFILE" -o StrictHostKeyChecking=no ${COMPOSE_DIR}/.env $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/

            # EC2에서 실행
            ssh -i "$KEYFILE" -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST '
              cd /home/$USER
              echo '$DOCKERHUB_PASSWORD' | docker login -u '$DOCKERHUB_USERNAME' --password-stdin
              docker compose down || true
              docker compose pull
              docker compose up -d --remove-orphans
              rm -f .env
            '

          '''
        }
      }
    }
  }
}
